'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const folders=new Map(),sha=x=>crypto.createHash('sha256').update(typeof x==='string'?x:Buffer.from(x)).digest('hex');let seq=0,sessionHeaders;
function iterator(array){let n=0;return {hasNext:()=>n<array.length,next:()=>array[n++]};}
function folder(name,parent){const o={id:'folder-'+(++seq),name,parent,children:[],files:[],description:'',private:true,getId(){return this.id;},getName(){return this.name;},getDescription(){return this.description;},setDescription(x){this.description=x;},getParents(){return iterator(this.parent?[this.parent]:[]);},getFoldersByName(name){return iterator(this.children.filter(x=>x.name===name));},createFolder(name){const f=folder(name,this);this.children.push(f);return f;},getFiles(){return iterator(this.files);},createFile(blob){const f={id:'file-'+(++seq),private:true,getId(){return this.id;},getName:()=>blob.getName(),getBlob:()=>blob,getSize:()=>blob.getBytes().length,isTrashed:()=>false,getSharingAccess(){return this.private?'PRIVATE':'ANYONE';},getViewers:()=>[],getEditors:()=>[]};this.files.push(f);return f;},isTrashed:()=>false,getSharingAccess(){return this.private?'PRIVATE':'DOMAIN';},getViewers:()=>[],getEditors:()=>[]};folders.set(o.id,o);return o;}
const root=folder('root');root.id='1ziePo6xoURvWw0o2IDwjEaO_tz6pE9bn';folders.set(root.id,root);
const ctx={console,Date,Number,JSON,Utilities:{getUuid:()=>crypto.randomUUID(),base64Encode:x=>Buffer.from(x).toString('base64')},TRBONB_sha_:sha,DriveApp:{Access:{PRIVATE:'PRIVATE'},getFolderById:id=>folders.get(id),getFileById:id=>[...folders.values()].flatMap(x=>x.files).find(x=>x.id===id)},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},ScriptApp:{getOAuthToken:()=> 'SERVER_ONLY_SECRET'},UrlFetchApp:{fetch:(url,opts)=>{sessionHeaders=opts.headers;return {getResponseCode:()=>200,getAllHeaders:()=>({Location:'https://www.googleapis.com/upload/drive/v3/files?upload_id=limited-file-session'})};}}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('integrations/onboarding/apps-script/CRM_OnboardingDrive.gs','utf8'),ctx);
const owner=ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_folder',group:'DDB',owner_key:'123'}).id;
const grant=ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_grant',practice_id:'a'.repeat(32),artist_folder_id:owner,slot:'identity_front',file:{name:'identity_front.pdf',size:12,mime:'application/pdf'}});
assert.equal(grant.upload_method,'PUT');assert.doesNotMatch(JSON.stringify(grant),/SERVER_ONLY_SECRET/);assert.equal(sessionHeaders.Authorization,'Bearer SERVER_ONLY_SECRET');
assert.throws(()=>ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_verify',folder_id:grant.folder_id,code:'wrong'}));
const blob={getBytes:()=>[...Buffer.from('%PDF-fixture')],getName:()=> 'identity_front.pdf',getDataAsString:()=>'%PDF-fixture'};
folders.get(grant.folder_id).createFile(blob);const verified=ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_verify',folder_id:grant.folder_id,code:grant.code});assert.equal(verified.sha256,sha('%PDF-fixture'));
const read=ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_read',folder_id:grant.folder_id,file_id:verified.file_id,sha256:verified.sha256});assert.equal(read.data,Buffer.from('%PDF-fixture').toString('base64'));
assert.throws(()=>ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_read',folder_id:grant.folder_id,file_id:'foreign-file',sha256:verified.sha256}));
root.private=false;assert.throws(()=>ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_health'}));root.private=true;
folders.get(grant.folder_id).files.push(folders.get(grant.folder_id).files[0]);assert.throws(()=>ctx.TRBONB_driveCommand_({action:'crm_onboarding_drive_verify',folder_id:grant.folder_id,code:grant.code}));
console.log('Drive private ancestry, isolated upload session, no bearer exposure, hash proof and ambiguous-file rejection verified.');
