<?php
/** Included only after current owner authentication and request CSRF validation. */
namespace TrbCrm;
if(!isset($runtime)||!$runtime instanceof OnboardingRuntime){http_response_code(404);exit;}
$esc=static fn($x)=>htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8');
$token=Security::csrf();$practices=$runtime->ledger->practices();$choices=$runtime->preparationChoices();
$states=['invited'=>'Invito preparato','identity_review'=>'Documenti da revisionare','identity_matched'=>'Documenti verificati','minor_blocked'=>'Maggiore età non confermata','payment_pending'=>'Primo versamento da confermare','owner_review'=>'In attesa della tua approvazione','signature_ready'=>'Documento definitivo da verificare','signature_pending'=>'Firma in corso / esito da verificare','activation_ready'=>'Registrazione disponibile','active'=>'Account attivo','cancelled'=>'Adesione annullata'];
$form=static function($id,$action,$label,$extra='')use($esc,$token){return '<form method="post"><input type="hidden" name="_csrf" value="'.$esc($token).'"><input type="hidden" name="id" value="'.$esc($id).'"><input type="hidden" name="action" value="'.$esc($action).'">'.$extra.'<button>'.$esc($label).'</button></form>';};
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nuove adesioni · TRB CRM</title><style>body{font:16px/1.6 system-ui,sans-serif;background:#f4f6f8;color:#172236;margin:0}main{max-width:1120px;margin:40px auto;padding:0 24px}a{color:#245ea8}article,section{background:white;border:1px solid #dce2eb;border-radius:12px;padding:24px;margin:20px 0}h1,h2{line-height:1.2}label{display:block}input,select,button{font:inherit;padding:10px;border:1px solid #bcc7d8;border-radius:6px}button{background:#172236;color:#fff;cursor:pointer}form{margin:12px 0}.actions{display:flex;flex-wrap:wrap;gap:12px}.notice{overflow-wrap:anywhere;background:#e5f0ff;padding:16px;border-radius:8px}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:8px;border-bottom:1px solid #ddd}.meta{color:#536078;font-size:14px}.fields{display:flex;flex-wrap:wrap;gap:16px}.fields input{max-width:180px}.fields label{max-width:100%;min-width:0}.fields select{width:100%;max-width:100%}button:disabled{opacity:.55;cursor:default}@media(max-width:600px){main{margin:24px auto;padding:0 16px}article,section{padding:16px}.fields{display:block}}summary{cursor:pointer}small{display:block}</style></head><body><main><a href="/">← CRM</a><h1>Nuove adesioni</h1><p>Documenti, versamenti confermati dal circuito, tua approvazione, firma di entrambe le parti e registrazione dell’account.</p>
<?php if($notice!==''):?><p class="notice" role="status"><?=$esc($notice)?></p><?php endif?>
<section><h2>Prepara una nuova adesione</h2><form method="post"><input type="hidden" name="_csrf" value="<?=$esc($token)?>"><input type="hidden" name="action" value="prepare"><div class="fields"><label>Proposta CRM non inviata<select required name="contract_id"><option value="">Scegli la proposta</option><?php foreach($choices['contracts'] as $c):?><option value="<?=$esc($c['id'])?>"><?=$esc($c['contract_number'].' · '.($c['artist_name']?:trim($c['first_name'].' '.$c['last_name'])).' · '.$c['template_key'])?></option><?php endforeach?></select></label></div><p>Sono disponibili le bozze e le anteprime generate non ancora inviate. Il modello è quello già assegnato alla proposta. I documenti saranno archiviati nella cartella privata Drive di questa adesione.</p><button <?=!$choices['contracts']?'disabled':''?>>Prepara proposta e collegamento personale</button></form><?php if(!$choices['contracts']):?><p class="meta">Non ci sono proposte disponibili. Dalla scheda candidatura, scegli il contratto e prepara l’anteprima; poi torna qui per avviare l’adesione.</p><?php endif?></section>
<?php if(!$practices):?><section><p>Nessuna adesione preparata con questo percorso.</p></section><?php endif?>
<?php foreach($practices as $p):?><article><h2><?=$esc($p['snapshot']['artist_name']?:$p['snapshot']['first_name'].' '.$p['snapshot']['last_name'])?></h2><p><?=$esc($p['snapshot']['contract_number'])?> · <?=$esc($p['snapshot']['group_code'])?> · <strong><?=$esc($states[$p['state']]??'Da verificare')?></strong></p><p class="meta"><?=$esc($p['email'])?> · pratica <?=$esc($p['id'])?></p>
<?php if($p['selected_plan']):?><p>Formula: <?=$esc($p['selected_plan']['label'])?><?php if($p['first_payment_date']):?> · primo versamento confermato <?=$esc($p['first_payment_date'])?><?php endif?></p><?php endif?>
<div class="actions"><?=$form($p['id'],'invite','Recupera collegamento personale')?><?=$form($p['id'],'refresh','Verifica versamenti e firma')?><?=$form($p['id'],'document','Apri proposta','<input type="hidden" name="slot" value="proposal">')?></div>
<details><summary>Documenti e dati amministrativi</summary><p>I dati letti automaticamente sono una trascrizione, soggetta alla tua verifica.</p><div class="actions"><?php foreach(['identity_front'=>'Identità fronte','identity_back'=>'Identità retro','tax_front'=>'Documento fiscale','tax_back'=>'Documento fiscale retro','contract'=>'Contratto firmato','signature_audit'=>'Prova di firma'] as $slot=>$label):?><?=$form($p['id'],'document',$label,'<input type="hidden" name="slot" value="'.$slot.'">')?><?php endforeach?></div><pre style="white-space:pre-wrap;overflow-wrap:anywhere"><?=$esc(json_encode($runtime->ledger->details($p['id']),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre></details>
<?php if(in_array($p['state'],['invited','identity_review'],true)):?><details><summary>Revisiona la trascrizione del documento</summary><form method="post"><input type="hidden" name="_csrf" value="<?=$esc($token)?>"><input type="hidden" name="action" value="review_identity"><input type="hidden" name="id" value="<?=$esc($p['id'])?>"><div class="fields"><label>Nomi stampati sul documento<input required name="first_name"></label><label>Cognome completo<input required name="last_name"></label><label>Data di nascita<input required type="date" name="birth_date"></label></div><button>Registra trascrizione revisionata</button></form></details><?php endif?>
<?php if($p['state']==='owner_review'):?><?=$form($p['id'],'approve','Approva dopo la verifica dei documenti e del primo versamento')?><?php endif?>
<?php if($p['state']==='signature_ready'):?><div class="actions"><?=$form($p['id'],'document','Verifica documento definitivo','<input type="hidden" name="slot" value="final_pdf">')?><?=$form($p['id'],'signature','Invia a OTPService','<label><input type="checkbox" required name="confirm_signature" value="1"> Ho verificato il documento definitivo e confermo l’invio alla firma.</label>')?></div><?php endif?>
<?php if($runtime->ledger->installments($p['id'])):?><details><summary>Scadenze e versamenti</summary><table><thead><tr><th>Quota</th><th>Scadenza</th><th>Importo</th><th>Confermato</th></tr></thead><tbody><?php foreach($runtime->ledger->installments($p['id']) as $r):?><tr><td><?=$esc($r['number'])?></td><td><?=$esc($r['due_date'])?></td><td>€ <?=$esc(number_format($r['amount_cents']/100,2,',','.'))?></td><td>€ <?=$esc(number_format($r['confirmed_cents']/100,2,',','.'))?></td></tr><?php endforeach?></tbody></table></details><?php endif?>
<?php if(!$p['cancelled_at']):?><details><summary>Annulla adesione</summary><?=$form($p['id'],'cancel','Conferma annullamento','<p>L’annullamento chiude questo percorso e interrompe nuove scadenze. I documenti e lo storico restano conservati.</p><label><input type="checkbox" required> Confermo l’annullamento della pratica.</label>')?></details><?php endif?>
</article><?php endforeach?></main></body></html>
