<?php
/** Included only after current owner authentication and request CSRF validation. */
namespace TrbCrm;
if(!isset($runtime)||!$runtime instanceof OnboardingRuntime){http_response_code(404);exit;}
$esc=static fn($x)=>htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8');
$token=Security::csrf();$practices=$runtime->ledger->practices();if(!empty($_GET['contract_id']))$practices=array_values(array_filter($practices,static fn($p)=>(int)$p['contract_id']===(int)$_GET['contract_id']));
$states=['invited'=>'Invito preparato','identity_review'=>'Documenti da revisionare','identity_matched'=>'Documenti verificati','minor_blocked'=>'Maggiore età non confermata','payment_pending'=>'Primo versamento da confermare','owner_review'=>'In attesa della tua approvazione','signature_ready'=>'Documento definitivo da verificare','signature_pending'=>'Firma in corso / esito da verificare','activation_ready'=>'Registrazione disponibile','active'=>'Account attivo','cancelled'=>'Adesione annullata'];
$form=static function($id,$action,$label,$extra='')use($esc,$token){return '<form method="post"><input type="hidden" name="_csrf" value="'.$esc($token).'"><input type="hidden" name="id" value="'.$esc($id).'"><input type="hidden" name="action" value="'.$esc($action).'">'.$extra.'<button>'.$esc($label).'</button></form>';};
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Attivazione contratti · TRB CRM</title><link rel="stylesheet" href="/assets/onboarding.css?v=20261001-2"></head><body class="onboarding-admin"><main><a href="/">← CRM</a><h1>Attivazione contratti</h1><p>Le pratiche si aprono automaticamente quando invii i contratti dalle candidature. Qui verifichi documenti, versamenti e firme dei contratti inviati.</p>
<?php if($notice!==''):?><p class="notice" role="status"><?=$esc($notice)?></p><?php endif?>
<?php if(!$practices):?><section><p>Nessuna adesione preparata con questo percorso.</p></section><?php endif?>
<?php foreach($practices as $p):?><article><h2><?=$esc($p['snapshot']['artist_name']?:$p['snapshot']['first_name'].' '.$p['snapshot']['last_name'])?></h2><p><?=$esc($p['snapshot']['contract_number'])?> · <?=$esc($p['snapshot']['group_code'])?> · <strong><?=$esc($states[$p['state']]??'Da verificare')?></strong></p><p class="meta"><?=$esc($p['email'])?> · pratica <?=$esc($p['id'])?></p>
<?php if($p['selected_plan']):?><p>Formula: <?=$esc($p['selected_plan']['label'])?><?php if($p['first_payment_date']):?> · primo versamento confermato <?=$esc($p['first_payment_date'])?><?php endif?></p><?php endif?>
<div class="actions"><?=$form($p['id'],'invite','Recupera collegamento personale')?><?=$form($p['id'],'refresh','Verifica versamenti e firma')?><?=$form($p['id'],'document','Apri proposta','<input type="hidden" name="slot" value="proposal">')?></div>
<details><summary>Documenti e dati amministrativi</summary><p>I dati letti automaticamente sono una trascrizione, soggetta alla tua verifica.</p><div class="actions"><?php foreach(['identity_front'=>'Identità fronte','identity_back'=>'Identità retro','tax_front'=>'Tessera sanitaria / codice fiscale fronte','tax_back'=>'Codice fiscale retro (pregresso)','contract'=>'Contratto firmato','signature_audit'=>'Prova di firma'] as $slot=>$label):?><?=$form($p['id'],'document',$label,'<input type="hidden" name="slot" value="'.$slot.'">')?><?php endforeach?></div><pre class="details-data"><?=$esc(json_encode($runtime->ledger->details($p['id']),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre></details>
<?php if(in_array($p['state'],['invited','identity_review'],true)):?><details><summary>Revisiona la trascrizione del documento</summary><form method="post"><input type="hidden" name="_csrf" value="<?=$esc($token)?>"><input type="hidden" name="action" value="review_identity"><input type="hidden" name="id" value="<?=$esc($p['id'])?>"><div class="fields"><label>Nomi stampati sul documento<input required name="first_name"></label><label>Cognome completo<input required name="last_name"></label><label>Data di nascita (carta d’identità)<input required type="date" name="birth_date"></label><label>Scadenza carta d’identità<input required type="date" name="expiry_date"></label><label>Nome sulla tessera sanitaria / codice fiscale<input required name="tax_first_name"></label><label>Cognome sulla tessera sanitaria / codice fiscale<input required name="tax_last_name"></label><label>Data di nascita sulla tessera sanitaria / codice fiscale<input required type="date" name="tax_birth_date"></label><label>Codice fiscale letto sul documento<input required name="tax_code"></label></div><button>Registra trascrizione revisionata</button></form></details><?php endif?>
<?php if($p['state']==='owner_review'):?><?=$form($p['id'],'approve','Approva dopo la verifica dei documenti e del primo versamento')?><?php endif?>
<?php if($p['state']==='signature_ready'):?><div class="actions"><?=$form($p['id'],'document','Verifica documento definitivo','<input type="hidden" name="slot" value="final_pdf">')?><?=$form($p['id'],'signature','Invia a OTPService','<label><input type="checkbox" required name="confirm_signature" value="1"> Ho verificato il documento definitivo e confermo l’invio alla firma.</label>')?></div><?php endif?>
<?php if($runtime->ledger->installments($p['id'])):?><details><summary>Scadenze e versamenti</summary><table><thead><tr><th>Quota</th><th>Scadenza</th><th>Importo</th><th>Confermato</th></tr></thead><tbody><?php foreach($runtime->ledger->installments($p['id']) as $r):?><tr><td><?=$esc($r['number'])?></td><td><?=$esc($r['due_date'])?></td><td>€ <?=$esc(number_format($r['amount_cents']/100,2,',','.'))?></td><td>€ <?=$esc(number_format($r['confirmed_cents']/100,2,',','.'))?></td></tr><?php endforeach?></tbody></table></details><?php endif?>
<?php if(!$p['cancelled_at']):?><details><summary>Annulla adesione</summary><?=$form($p['id'],'cancel','Conferma annullamento','<p>L’annullamento chiude questo percorso e interrompe nuove scadenze. I documenti e lo storico restano conservati.</p><label><input type="checkbox" required> Confermo l’annullamento della pratica.</label>')?></details><?php endif?>
</article><?php endforeach?></main></body></html>
