<?php
if(!defined('ABSPATH'))exit;
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: private, no-store, max-age=0');
header('Referrer-Policy: no-referrer');header('X-Robots-Tag: noindex, nofollow');
header("Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://www.googleapis.com; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
$config=['endpoint'=>rest_url('trb/v1/onboarding/public'),'csrf'=>trb_onboarding_csrf((string)($_COOKIE['__Host-trb_onboarding']??'')),'enabled'=>trb_onboarding_enabled(),'account'=>isset($_GET['account']),'logged_in'=>is_user_logged_in(),'login_url'=>home_url('/accedi/'),'support_url'=>home_url('/segnalazione/')];
?><!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Adesione · TRB rec</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{font:16px/1.6 system-ui,sans-serif;background:#f4f6f8;color:#19283e;margin:0}main{max-width:840px;margin:40px auto;padding:0 24px}header{border-bottom:1px solid #d9e1ee;padding-bottom:24px}.brand{font-size:20px;font-weight:750;letter-spacing:.04em}h1,h2{line-height:1.25}h1{font-size:34px}section{background:#fff;border:1px solid #dce3ed;border-radius:12px;padding:24px;margin:20px 0}label{display:block;margin:10px 0}input:not([type=checkbox]):not([type=radio]),select{font:inherit;border:1px solid #b1bfd2;padding:11px;border-radius:6px;width:100%}button,.button{font:inherit;background:#19283e;color:white;padding:12px 18px;border:0;border-radius:6px;cursor:pointer;display:inline-block;text-decoration:none}button:disabled{opacity:.55;cursor:wait}a{color:#245b9a}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.muted{color:#52627b;font-size:14px}.notice{background:#e7effb;padding:16px;border-radius:8px;overflow-wrap:anywhere}.error{background:#fff0ea;color:#7f2b13}[hidden]{display:none!important}.upload-status{display:block;margin-top:8px;overflow-wrap:anywhere}input[type=file]{max-width:100%;font-size:14px}h3{margin-top:24px}.upload-progress{margin:20px 0;padding:16px;background:#e7effb;border-radius:8px;scroll-margin:24px}.upload-progress strong{display:block}.upload-progress progress{display:block;width:100%;height:18px;margin:12px 0;accent-color:#245b9a}.upload-row{margin:16px 0;padding:16px 0;border-top:1px solid #e6eaf0}.plan{border:1px solid #c9d5e6;border-radius:8px;padding:16px}.plan input{margin-right:8px}table{width:100%;border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:16px}@media(max-width:600px){main{padding:0 16px;margin-top:24px}section{padding:20px}.grid{grid-template-columns:1fr}h1{font-size:28px}table{font-size:14px}}
</style></head><body><main><header><div class="brand">TRB rec</div><h1>La tua adesione</h1><p>Compila i tuoi dati e carica i due documenti richiesti. Ti guideremo fino alla firma e alla creazione del tuo account.</p></header><p id="notice" class="notice" role="status" aria-live="polite" hidden></p>
<section id="email-step"><h2>Conferma il tuo indirizzo email</h2><p>Il codice viene inviato all’indirizzo indicato nella tua proposta.</p><button id="send-code" type="button">Invia codice di accesso</button><form id="email-form" hidden><label>Codice ricevuto<input name="code" required inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6"></label><button>Conferma email</button></form></section>
<section id="practice-summary" hidden><h2 id="artist-title"></h2><p id="practice-status"></p><div class="actions"><button id="refresh" type="button">Aggiorna stato</button><button data-document="proposal" type="button">Leggi la proposta</button><button data-document="contract" id="signed-contract" type="button" hidden>Contratto firmato</button><button data-document="signature_audit" id="signature-audit" type="button" hidden>Prova di firma</button></div></section>
<section id="details-step" hidden><h2>Dati e documenti</h2><p>Completa questa pagina, poi premi «Salva e continua».</p><h3>Dati amministrativi</h3><form id="details-form"><div class="grid"><label>Indirizzo<input required name="address_1" autocomplete="street-address"></label><label>Città<input required name="city" autocomplete="address-level2"></label><label>CAP<input required name="postcode" autocomplete="postal-code"></label><label>Paese (codice di due lettere)<input required name="country" value="IT" pattern="[A-Za-z]{2}" maxlength="2" autocomplete="country"></label><label>Provincia / regione<input name="state" autocomplete="address-level1"></label><label>Cellulare italiano per la firma (anche con +39)<input required name="phone" type="tel" autocomplete="tel"></label><label>Codice fiscale<input required name="tax_code" autocapitalize="characters"></label><label>Partita IVA (se applicabile)<input name="vat_number"></label><label>Codice SDI (facoltativo)<input name="sdi_code" maxlength="7"></label><label>PEC (facoltativa)<input name="pec" type="email"></label></div><div id="documents-step"><h3>Documenti richiesti</h3><p>Carica solo il fronte della carta d’identità e il fronte della tessera sanitaria o del tesserino del codice fiscale. Usa foto complete e leggibili o PDF, fino a 10 MB per file.</p><div id="upload-list"></div><div id="upload-progress" class="upload-progress" role="status" aria-live="polite" hidden><strong id="upload-progress-label">Caricamento in corso…</strong><progress id="upload-progress-bar" max="100" aria-label="Avanzamento complessivo del caricamento"></progress><span id="upload-progress-value" class="muted">Attendi senza chiudere questa pagina.</span></div></div><p class="muted">Verificheremo che i dati dei documenti corrispondano a quelli della proposta contrattuale. Al termine della verifica potrai proseguire. I documenti sono conservati nell’archivio privato di TRB rec e utilizzati per la gestione della tua adesione, del contratto e degli adempimenti amministrativi e fiscali.</p><?php $privacy_url=get_privacy_policy_url();if($privacy_url): ?><p class="muted"><a href="<?php echo esc_url($privacy_url); ?>" target="_blank" rel="noopener">Leggi l’informativa sul trattamento dei dati personali</a></p><?php endif; ?><label><input type="checkbox" required name="privacy_acknowledged"> Ho letto le informazioni sul trattamento dei dati e dei documenti.</label><button id="save-and-continue">Salva e continua</button></form></section>
<section id="plans-step" hidden><h2>Formula contrattuale</h2><form id="plans-form"><div id="plan-list"></div><label><input type="checkbox" required name="proposal_read"> Ho letto la proposta e confermo la formula selezionata.</label><button>Conferma formula</button></form><p id="plan-schedule-note" class="muted">Le scadenze mensili partono dalla data del primo versamento confermato dal circuito, mantenendo lo stesso giorno del mese. Quando il mese è più corto si usa il suo ultimo giorno.</p></section>
<section id="payment-step" hidden><h2 id="payment-title">Versamenti</h2><p id="selected-plan-summary"></p><p id="payment-note"></p><div id="installments" style="overflow-x:auto"></div><button id="checkout" type="button">EFFETTUA IL VERSAMENTO</button><p class="muted">Scegli PayPal o una carta di credito/debito abilitata ai pagamenti online. Dopo il versamento, torna qui e aggiorna lo stato: potrai proseguire quando il circuito avrà confermato il pagamento.</p></section>
<section id="register-step" hidden><h2>Crea il tuo account artista</h2><p>Il contratto è firmato e archiviato. Scegli la password per accedere al portale.</p><form id="register-form"><label>Password (almeno 14 caratteri)<input required name="password" type="password" minlength="14" maxlength="128" autocomplete="new-password"></label><label>Ripeti password<input required name="repeat_password" type="password" minlength="14" maxlength="128" autocomplete="new-password"></label><button>Crea account e accedi</button></form></section>
<footer><?php if($privacy_url): ?><p><a href="<?php echo esc_url($privacy_url); ?>" target="_blank" rel="noopener">Informativa privacy</a></p><?php endif; ?><p>Hai bisogno di assistenza? Rispondi all’email con cui TRB rec ti ha inviato la proposta.</p></footer></main><script>window.TRBOnboarding=<?=wp_json_encode($config,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src="<?=esc_url(get_template_directory_uri().'/assets/js/onboarding/onboarding.js')?>?v=2026.2.20261002b" defer></script></body></html>
