<?php
if(!defined('ABSPATH'))exit;
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: private, no-store, max-age=0');
header('Referrer-Policy: no-referrer');header('X-Robots-Tag: noindex, nofollow');
header("Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://www.googleapis.com; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
$welcome=isset($_GET['accesso']);
$config=['welcome'=>$welcome,'endpoint'=>rest_url('trb/v1/onboarding/public'),'csrf'=>trb_onboarding_csrf((string)($_COOKIE['__Host-trb_onboarding']??'')),'enabled'=>trb_onboarding_enabled(),'account'=>isset($_GET['account']),'logged_in'=>is_user_logged_in(),'login_url'=>home_url('/accedi/'),'support_url'=>home_url('/segnalazione/')];
?><!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$welcome?'Accesso al Portale Artisti':'Adesione · TRB rec'?></title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{font:16px/1.6 system-ui,sans-serif;background:#f4f6f8;color:#19283e;margin:0}main{max-width:840px;margin:40px auto;padding:0 24px}header{border-bottom:1px solid #d9e1ee;padding-bottom:24px}.brand{font-size:20px;font-weight:750;letter-spacing:.04em}h1,h2{line-height:1.25}h1{font-size:34px}section{background:#fff;border:1px solid #dce3ed;border-radius:12px;padding:24px;margin:20px 0}label{display:block;margin:10px 0}input:not([type=checkbox]):not([type=radio]),select{font:inherit;border:1px solid #b1bfd2;padding:11px;border-radius:6px;width:100%}button,.button{font:inherit;background:#19283e;color:white;padding:12px 18px;border:0;border-radius:6px;cursor:pointer;display:inline-block;text-decoration:none}button:disabled{opacity:.55;cursor:wait}a{color:#245b9a}#signature-email{overflow-wrap:anywhere;background:#f4f6f8;padding:12px 16px;border-radius:8px}.secondary{background:transparent;color:#245b9a;padding:0;text-decoration:underline}.is-error{color:#7f2b13}input[readonly]{background:#f4f6f8}summary{cursor:pointer;color:#245b9a}details{margin:20px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.muted{color:#52627b;font-size:14px}.notice{background:#e7effb;padding:16px;border-radius:8px;overflow-wrap:anywhere}.error{background:#fff0ea;color:#7f2b13}[hidden]{display:none!important}.upload-status{display:block;margin-top:8px;overflow-wrap:anywhere}input[type=file]{max-width:100%;font-size:14px}h3{margin-top:24px}.upload-progress{margin:20px 0;padding:16px;background:#e7effb;border-radius:8px;scroll-margin:24px}.upload-progress strong{display:block}.upload-progress progress{display:block;width:100%;height:18px;margin:12px 0;accent-color:#245b9a}.upload-row{margin:16px 0;padding:16px 0;border-top:1px solid #e6eaf0}.plan{border:1px solid #c9d5e6;border-radius:8px;padding:16px}.plan input{margin-right:8px}table{width:100%;border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:16px}.activation-view{max-width:560px}.activation-view header{border:0;padding-bottom:0}.activation-view button,.activation-view .button{width:100%;text-align:center;background:#AFEBD2;color:#183C2D;font-weight:700}.activation-view section{margin-top:20px}.activation-view footer{font-size:14px}.activation-view h1{font-size:30px;overflow-wrap:anywhere}@media(max-width:600px){main{padding:0 16px;margin-top:24px}section{padding:20px}.grid{grid-template-columns:1fr}h1{font-size:28px}table{font-size:14px}}
</style></head><body><main id="onboarding-main" class="<?=$welcome?'activation-view':''?>"><header><div id="page-brand" class="brand">TRB rec</div><h1 id="page-title"><?=$welcome?'Accedi al Portale Artisti':'La tua adesione'?></h1><p id="page-intro"><?=$welcome?'Conferma il tuo indirizzo email per impostare la password ed entrare nel portale.':'Segui i passaggi indicati qui sotto per firmare il contratto e attivare il tuo accesso al Portale Artisti.'?></p></header><p id="notice" class="notice" role="status" aria-live="polite" hidden></p>
<section id="email-step"><h2>Conferma il tuo indirizzo email</h2><p>Il codice viene inviato all’indirizzo indicato nella tua proposta.</p><button id="send-code" type="button">Invia codice di accesso</button><form id="email-form" hidden><label>Codice ricevuto<input name="code" required inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6"></label><button>Conferma email</button></form></section>
<section id="practice-summary" hidden><h2 id="artist-title"></h2><p id="practice-status" class="muted"></p><h3 id="next-step-title"></h3><p id="next-step-help" aria-live="polite"></p><div id="signature-email" hidden><p><strong>L’email da cercare</strong></p><p>A: <strong id="signature-recipient"></strong><br>Mittente: <strong id="signature-sender"></strong><br>Oggetto: <strong id="signature-subject"></strong></p></div><p id="automatic-status" class="muted" hidden>Questa pagina si aggiorna automaticamente. Puoi anche chiuderla e riaprire il collegamento ricevuto via email.</p><div class="actions"><button id="refresh" type="button" hidden>Riprova la verifica</button><button id="read-proposal" class="secondary" data-document="proposal" type="button">Consulta la proposta ricevuta</button><button data-document="contract" id="signed-contract" type="button" hidden>Contratto firmato</button><button data-document="signature_audit" id="signature-audit" type="button" hidden>Prova di firma</button></div></section>
<section id="details-step" hidden><h2>Dati e documenti</h2><p>Completa questa pagina, poi premi «Salva e continua».</p><h3>Dati amministrativi</h3><form id="details-form"><div class="grid">
<label>Nome<input name="first_name" readonly autocomplete="given-name"></label><label>Cognome<input name="last_name" readonly autocomplete="family-name"></label>
<label>Email<input name="email" type="email" readonly autocomplete="email"></label><label>Cellulare italiano per la firma<input required name="phone" type="tel" data-trb-mobile autocomplete="tel" placeholder="+39 333 1234567"></label>
<label>Data di nascita<input required name="birth_date" type="date" max="<?=esc_attr(wp_date('Y-m-d'))?>" autocomplete="bday"></label>
<label>Comune di nascita<input required name="birth_place" data-trb-birthplace list="trb-birthplace-options" autocomplete="off"><datalist id="trb-birthplace-options"></datalist><small class="muted" data-trb-birthplace-status>Scrivi il Comune e selezionalo tra quelli proposti.</small></label>
<label>Provincia di nascita<input name="birth_province" data-trb-birth-province readonly></label>
<label>Codice fiscale<input required name="tax_code" data-trb-tax-code minlength="16" maxlength="16" autocapitalize="characters" autocomplete="off"><small class="muted">16 caratteri: lettere e numeri come sul documento.</small></label>
<label>Numero carta d’identità elettronica<input required name="document_number" data-trb-document-number maxlength="9" pattern="[A-Za-z]{2}[0-9]{5}[A-Za-z]{2}" autocapitalize="characters" placeholder="CA12345AB"></label>
<label>Scadenza carta d’identità<input required name="document_expiry" data-trb-document-expiry type="date" min="<?=esc_attr(wp_date('Y-m-d'))?>" max="<?=esc_attr((new DateTimeImmutable('today',wp_timezone()))->modify('+10 years')->format('Y-m-d'))?>"></label>
<label>Indirizzo di residenza<input required name="street" autocomplete="address-line1" maxlength="160"></label><label>Numero civico<input required name="street_number" autocomplete="address-line2" maxlength="30" placeholder="Es. 11/A"></label>
<label>CAP<input required name="postcode" data-trb-postcode inputmode="numeric" pattern="[0-9]{5}" maxlength="5" autocomplete="postal-code"><small class="muted" data-trb-postcode-status>Inserisci il CAP: Comune e provincia si compilano automaticamente.</small></label>
<label>Comune di residenza<select required name="city" data-trb-city autocomplete="address-level2"><option value="">Inserisci prima il CAP</option></select></label>
<label>Provincia<input name="state" data-trb-province readonly autocomplete="address-level1"></label><label>Paese<input name="country" data-trb-country value="Italia" readonly autocomplete="country-name"></label>
</div><details id="invoice-fields"><summary>Dati per la fatturazione (facoltativi)</summary><div class="grid"><label>Ragione sociale<input name="company_name" maxlength="200"></label><label>Indirizzo di fatturazione<input name="company_address" maxlength="200"></label><label>Partita IVA<input name="vat_number" maxlength="32"></label><label>Codice SDI<input name="sdi_code" maxlength="7"></label><label>PEC<input name="pec" type="email" maxlength="255"></label></div></details><div id="documents-step"><h3>Documenti richiesti</h3><p>Carica solo il fronte della carta d’identità e il fronte della tessera sanitaria o del tesserino del codice fiscale. Usa foto complete e leggibili o PDF, fino a 10 MB per file.</p><div id="upload-list"></div><div id="upload-progress" class="upload-progress" role="status" aria-live="polite" hidden><strong id="upload-progress-label">Caricamento in corso…</strong><progress id="upload-progress-bar" max="100" aria-label="Avanzamento complessivo del caricamento"></progress><span id="upload-progress-value" class="muted">Attendi senza chiudere questa pagina.</span></div></div><p class="muted">Verificheremo che i dati dei documenti corrispondano a quelli della proposta contrattuale. Al termine della verifica potrai proseguire. I documenti sono conservati nell’archivio privato di TRB rec e utilizzati per la gestione della tua adesione, del contratto e degli adempimenti amministrativi e fiscali.</p><?php $privacy_url=get_privacy_policy_url();if($privacy_url): ?><p class="muted"><a href="<?php echo esc_url($privacy_url); ?>" target="_blank" rel="noopener">Leggi l’informativa sul trattamento dei dati personali</a></p><?php endif; ?><label><input type="checkbox" required name="privacy_acknowledged"> Ho letto le informazioni sul trattamento dei dati e dei documenti.</label><button id="save-and-continue">Salva e continua</button></form></section>
<section id="plans-step" hidden><h2>Formula contrattuale</h2><form id="plans-form"><div id="plan-list"></div><label><input type="checkbox" required name="proposal_read"> Ho letto la proposta e confermo la formula selezionata.</label><button>Conferma formula</button></form><p id="plan-schedule-note" class="muted">Le scadenze mensili partono dalla data del primo versamento confermato dal circuito, mantenendo lo stesso giorno del mese. Quando il mese è più corto si usa il suo ultimo giorno.</p></section>
<section id="payment-step" hidden><h2 id="payment-title">Versamenti</h2><p id="selected-plan-summary"></p><p id="payment-note"></p><div id="installments" style="overflow-x:auto"></div><button id="checkout" type="button">EFFETTUA IL VERSAMENTO</button><p class="muted">Scegli PayPal o una carta di credito/debito abilitata ai pagamenti online. Dopo il versamento, torna qui: la pagina si aggiorna automaticamente e potrai proseguire quando il circuito avrà confermato il pagamento.</p></section>
<section id="ready-access" hidden><h2>Il tuo account è pronto</h2><p>Usa il tuo indirizzo email e la password che hai scelto.</p><a id="portal-access" class="button" href="<?=esc_url(home_url('/accedi/'))?>" hidden>Accedi al Portale Artisti</a></section>
<section id="register-step" hidden><h2>Scegli la tua password</h2><p>Imposta una password personale. La userai anche per i prossimi accessi.</p><form id="register-form"><label>Password (almeno 10 caratteri)<input required name="password" type="password" minlength="10" maxlength="128" autocomplete="new-password"></label><label>Ripeti password<input required name="repeat_password" type="password" minlength="10" maxlength="128" autocomplete="new-password"></label><button>Imposta la password e accedi</button></form></section>
<footer><?php if($privacy_url): ?><p><a href="<?php echo esc_url($privacy_url); ?>" target="_blank" rel="noopener">Informativa privacy</a></p><?php endif; ?><p>Hai bisogno di assistenza? Rispondi all’email ricevuta da TRB rec.</p></footer></main><script>window.TRBOnboarding=<?=wp_json_encode($config,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src="<?=esc_url(get_template_directory_uri().'/assets/js/trb-artist-profile.js')?>?v=20261003g" defer></script><script src="<?=esc_url(get_template_directory_uri().'/assets/js/onboarding/onboarding.js')?>?v=2026.2.20261003g" defer></script></body></html>


