/** All folders stay private. Browser grants authorize one fixed-size file only. */
var TRBONB_DRIVE_ROOT='1ziePo6xoURvWw0o2IDwjEaO_tz6pE9bn';
function TRBONB_drivePrivate_(folder){if(folder.isTrashed()||folder.getSharingAccess()!==DriveApp.Access.PRIVATE||folder.getViewers().length||folder.getEditors().length)throw new Error('Archivio adesioni non privato.');return folder;}
function TRBONB_driveRoot_(){return TRBONB_drivePrivate_(DriveApp.getFolderById(TRBONB_DRIVE_ROOT));}
function TRBONB_driveChild_(parent,name){var found=parent.getFoldersByName(name),folder=found.hasNext()?found.next():parent.createFolder(name);if(found.hasNext())throw new Error('Archivio ambiguo.');folder.setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.NONE);return TRBONB_drivePrivate_(folder);}
function TRBONB_driveOwner_(id){var folder=TRBONB_drivePrivate_(DriveApp.getFolderById(String(id))),parents=folder.getParents();if(!parents.hasNext())throw new Error('Cartella adesione non associata.');var group=TRBONB_drivePrivate_(parents.next()),roots=group.getParents();if(parents.hasNext()||!roots.hasNext()||roots.next().getId()!==TRBONB_driveRoot_().getId()||roots.hasNext())throw new Error('Cartella fuori archivio adesioni.');return folder;}
function TRBONB_driveGrant_(folderId,code){var folder=TRBONB_drivePrivate_(DriveApp.getFolderById(String(folderId))),parents=folder.getParents(),grant=JSON.parse(folder.getDescription()||'null');if(!grant||!parents.hasNext()||parents.next().getId()!==grant.artist_folder_id||parents.hasNext()||!code||TRBONB_sha_(String(code))!==grant.code_sha256)throw new Error('Caricamento non associato.');TRBONB_driveOwner_(grant.artist_folder_id);return {folder:folder,grant:grant};}
function TRBONB_driveFile_(folder){var files=folder.getFiles(),file=files.hasNext()?files.next():null;if(!file||files.hasNext()||file.isTrashed()||file.getSize()<1||file.getSize()>10485760||file.getSharingAccess()!==DriveApp.Access.PRIVATE||file.getViewers().length||file.getEditors().length)throw new Error('Documento assente, ambiguo o non privato.');return file;}
function TRBONB_driveMime_(blob,slot){var bytes=blob.getBytes(),prefix=String.fromCharCode.apply(null,bytes.slice(0,16).map(function(x){return (x+256)%256;}));if(prefix.slice(0,5)==='%PDF-')return 'application/pdf';if((bytes[0]+256)%256===137&&prefix.slice(1,4)==='PNG')return 'image/png';if((bytes[0]+256)%256===255&&(bytes[1]+256)%256===216&&(bytes[2]+256)%256===255)return 'image/jpeg';if(slot==='signature_audit'&&/<AuditTrail[ >]/.test(blob.getDataAsString()))return 'application/xml';throw new Error('Formato documento non valido.');}
function TRBONB_driveMetadata_(folder,grant){var file=TRBONB_driveFile_(folder),blob=file.getBlob(),sha=TRBONB_sha_(blob.getBytes()),mime=TRBONB_driveMime_(blob,grant.slot);if(grant.file_size&&file.getSize()!==grant.file_size)throw new Error('Dimensione caricamento discordante.');if(grant.sha256&&grant.sha256!==sha)throw new Error('Documento archiviato modificato.');if(grant.file_id&&grant.file_id!==file.getId())throw new Error('Documento archiviato sostituito.');grant.sha256=sha;grant.file_id=file.getId();grant.closed=true;folder.setDescription(JSON.stringify(grant));return {file_id:file.getId(),folder_id:folder.getId(),artist_folder_id:grant.artist_folder_id,hash:sha,sha256:sha,size:file.getSize(),name:file.getName(),mime:mime,provider:'google_drive'};}
function TRBONB_driveCommand_(p){
 if(p.action==='crm_onboarding_drive_health'){var root=TRBONB_driveRoot_();var response=UrlFetchApp.fetch('https://www.googleapis.com/drive/v3/files/'+root.getId()+'?fields=id,mimeType',{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true});if(response.getResponseCode()!==200)throw new Error('API Drive non confermata.');return {success:true,provider:'google_drive',private:true,root_id:root.getId()};}
 var lock=LockService.getScriptLock();lock.waitLock(30000);try{
 if(p.action==='crm_onboarding_drive_folder'){if(['TRB','DDS','DDB','DDB12','DDB-TRB'].indexOf(p.group)<0||!/^\d+$/.test(p.owner_key)&&!/^[-_A-Za-z0-9]{10,128}$/.test(p.owner_key))throw new Error('Destinazione adesione non valida.');if(/^\d+$/.test(p.owner_key)){var group=TRBONB_driveChild_(TRBONB_driveRoot_(),p.group),owner=TRBONB_driveChild_(group,'Contratto-'+p.owner_key);return {success:true,id:owner.getId()};}var existing=TRBONB_driveOwner_(p.owner_key),parents=existing.getParents();if(parents.next().getName()!==p.group)throw new Error('Gruppo archivio discordante.');return {success:true,id:existing.getId()};}
 if(p.action==='crm_onboarding_drive_grant'){
  if(['identity_front','identity_back','tax_front','tax_back','proposal','final_pdf','signed_pdf','signature_audit'].indexOf(p.slot)<0)throw new Error('Documento non ammesso.');var owner=TRBONB_driveOwner_(p.artist_folder_id),code=TRBONB_sha_(Utilities.getUuid()+Utilities.getUuid()),folder=owner.createFolder(p.slot+'-'+code.slice(0,12)).setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.NONE),expires=new Date(Date.now()+7200000),meta={practice_id:p.practice_id,slot:p.slot,artist_folder_id:owner.getId(),code_sha256:TRBONB_sha_(code),expires_at:expires.toISOString(),closed:false};var out={success:true,provider:'google_drive',slot:p.slot,practice_id:p.practice_id,folder_id:folder.getId(),artist_folder_id:owner.getId(),upload_link_id:code,code:code,expires_at:meta.expires_at,max_bytes:10485760};
  if(['identity_front','identity_back','tax_front','tax_back'].indexOf(p.slot)>=0){var info=p.file||{},mime=info.mime,size=info.size,name=String(info.name||'');if(['application/pdf','image/png','image/jpeg'].indexOf(mime)<0||!Number.isInteger(size)||size<1||size>10485760||!/^[-_A-Za-z0-9. ]{1,160}\.(pdf|png|jpe?g)$/i.test(name))throw new Error('Dati caricamento non validi.');meta.file_size=size;var placeholder=folder.createFile(Utilities.newBlob('',mime,name)).setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.NONE);var r=UrlFetchApp.fetch('https://www.googleapis.com/upload/drive/v3/files/'+placeholder.getId()+'?uploadType=resumable&fields=id',{method:'patch',contentType:'application/json',headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken(),'X-Upload-Content-Type':mime,'X-Upload-Content-Length':String(size)},payload:JSON.stringify({name:name,mimeType:mime}),muteHttpExceptions:true});var headers=r.getAllHeaders(),session=headers.Location||headers.location;if(r.getResponseCode()!==200||!/^https:\/\/www\.googleapis\.com\/upload\/drive\/v3\/files\/[A-Za-z0-9_-]+\?/.test(session||''))throw new Error('Caricamento Drive non disponibile.');out.upload_endpoint=session;out.upload_method='PUT';}
  folder.setDescription(JSON.stringify(meta));return out;
 }
 if(p.action==='crm_onboarding_drive_verify'){var checked=TRBONB_driveGrant_(p.folder_id,p.code);if(!checked.grant.closed&&Date.parse(checked.grant.expires_at)<Date.now())throw new Error('Caricamento scaduto.');return Object.assign({success:true},TRBONB_driveMetadata_(checked.folder,checked.grant));}
 if(p.action==='crm_onboarding_drive_read'){var parent=TRBONB_drivePrivate_(DriveApp.getFolderById(String(p.folder_id))),grant=JSON.parse(parent.getDescription()||'null');if(!grant||!grant.closed||grant.file_id!==p.file_id||grant.sha256!==p.sha256)throw new Error('Documento non associato alla pratica.');TRBONB_driveOwner_(grant.artist_folder_id);var metadata=TRBONB_driveMetadata_(parent,grant),blob=DriveApp.getFileById(metadata.file_id).getBlob();return Object.assign({success:true,data:Utilities.base64Encode(blob.getBytes())},metadata);}
 throw new Error('Operazione archivio non ammessa.');
 }finally{lock.releaseLock();}
}
function TRBONB_driveUpload_(blob,grant){var checked=TRBONB_driveGrant_(grant.folder_id,grant.code),meta=checked.grant;if(meta.practice_id!==grant.practice_id||meta.artist_folder_id!==grant.artist_folder_id||meta.slot!==grant.slot)throw new Error('Documento non associato alla pratica.');var sha=TRBONB_sha_(blob.getBytes());if(meta.closed){if(meta.sha256!==sha)throw new Error('Documento definitivo discordante.');return;}if(Date.parse(meta.expires_at)<Date.now()||blob.getBytes().length<1||blob.getBytes().length>10485760)throw new Error('Caricamento scaduto o troppo grande.');var files=checked.folder.getFiles();if(files.hasNext()){var existing=TRBONB_driveFile_(checked.folder);if(TRBONB_sha_(existing.getBlob().getBytes())!==sha)throw new Error('Documento esistente discordante.');}else checked.folder.createFile(blob).setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.NONE);TRBONB_driveMetadata_(checked.folder,meta);}

function TRBONB_driveSetup(){var root=DriveApp.getFolderById(TRBONB_DRIVE_ROOT);root.setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.NONE);console.log(JSON.stringify({private:TRBONB_driveRoot_().getId()===TRBONB_DRIVE_ROOT}));}

/** Synthetic file only: exercise the same resumable session and authenticated read. */
function TRBONB_driveSmoke(){
 var health=TRBONB_driveCommand_({action:'crm_onboarding_drive_health'}),owner=TRBONB_driveCommand_({action:'crm_onboarding_drive_folder',group:'TRB',owner_key:'999999999'}),blob=Utilities.newBlob('%PDF-TRB-ARCHIVE-QA','application/pdf','identity_front.pdf'),grant=TRBONB_driveCommand_({action:'crm_onboarding_drive_grant',practice_id:'ffffffffffffffffffffffffffffffff',artist_folder_id:owner.id,slot:'identity_front',file:{name:'identity_front.pdf',size:blob.getBytes().length,mime:'application/pdf'}});
 var upload=UrlFetchApp.fetch(grant.upload_endpoint,{method:'put',contentType:'application/pdf',payload:blob.getBytes(),muteHttpExceptions:true});
 if([200,201].indexOf(upload.getResponseCode())<0)throw new Error('Caricamento collaudo non confermato.');
 var file=TRBONB_driveCommand_({action:'crm_onboarding_drive_verify',folder_id:grant.folder_id,code:grant.code}),read=TRBONB_driveCommand_({action:'crm_onboarding_drive_read',folder_id:file.folder_id,file_id:file.file_id,sha256:file.sha256});
 if(file.sha256!==TRBONB_sha_(blob.getBytes())||read.data!==Utilities.base64Encode(blob.getBytes()))throw new Error('Verifica collaudo discordante.');
 console.log(JSON.stringify({archive_private:health.private,direct_session_upload:true,hash_verified:true,authenticated_read:true}));DriveApp.getFolderById(owner.id).setTrashed(true);
}
