/* Admin-only. Exact element manifest and optimistic concurrency are enforced server-side. */
(async()=>{'use strict';const c=window.TRBStudio;if(!c)return;
 const panel=document.createElement('aside');panel.id='trb-studio-panel';panel.setAttribute('aria-label','Editor visivo TRB');
 panel.innerHTML='<h2>Modifica visiva</h2><p>Seleziona un testo evidenziato nella pagina.</p><label for="trb-studio-text">Testo</label><textarea id="trb-studio-text" disabled></textarea><details><summary>Spazi e larghezza</summary><div id="trb-studio-spacing"></div></details><button type="button" id="trb-studio-save" disabled>Salva</button><button type="button" class="studio-secondary" id="trb-studio-cancel">Annulla</button><a class="studio-secondary" id="trb-studio-native">Editor completo</a><p id="trb-studio-status" role="status" aria-live="polite">Caricamento…</p>';
 document.body.append(panel);const status=panel.querySelector('[role=status]'),text=panel.querySelector('textarea'),save=panel.querySelector('#trb-studio-save');panel.querySelector('#trb-studio-native').href=c.native;
 const sourceLabel=document.createElement('label'),sourceSelect=document.createElement('select');sourceLabel.textContent='Area da modificare';sourceLabel.htmlFor='trb-studio-source';sourceSelect.id='trb-studio-source';for(const source of c.sources){const option=document.createElement('option');option.value=source.id;option.textContent=source.label;option.selected=source.id===c.postId;sourceSelect.append(option);}panel.querySelector('h2').after(sourceLabel,sourceSelect);
 const pending=new Map(),targets=new Map();let selected=null,manifest;
 const norm=s=>s.replace(/\s+/g,' ').trim();
 const request=async(method,body)=>{const r=await fetch(c.endpoint+c.postId,{method,credentials:'same-origin',headers:{'X-WP-Nonce':c.nonce,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.message||'Salvataggio non riuscito.');return d;};
 try{manifest=await request('GET');for(const item of manifest.items){const selector=c.scope.split(',').map(s=>s+' '+item.tag).join(',');const matches=[...document.querySelectorAll(selector)].filter(e=>!e.closest('form,script,style,#trb-studio-panel')&&norm(e.textContent)===norm(item.text));if(matches.length!==1)continue;const e=matches[0];e.dataset.trbStudioKey=item.key;targets.set(item.key,{e,item,original:e.innerHTML});}status.textContent='Pronto. '+targets.size+' testi modificabili. I moduli si gestiscono dall’editor completo.';}catch(e){status.textContent=e.message;return;}
 sourceSelect.addEventListener('change',()=>{if(pending.size&&!confirm('Scartare le modifiche e cambiare area?')){sourceSelect.value=c.postId;return;}pending.clear();const url=new URL(c.exit);url.searchParams.set('trb-edit','1');url.searchParams.set('trb-edit-source',sourceSelect.value);location.assign(url);});
 const fields=[['margin-top','Margine superiore',0,160],['margin-bottom','Margine inferiore',0,160],['padding-top','Spazio interno sopra',0,160],['padding-bottom','Spazio interno sotto',0,160],['padding-left','Spazio interno a sinistra',0,96],['padding-right','Spazio interno a destra',0,96],['max-width','Larghezza massima',240,1440]];
 for(const [prop,label,min,max] of fields){const id='studio-'+prop,l=document.createElement('label'),input=document.createElement('input');l.htmlFor=id;l.textContent=label+' (px)';input.id=id;input.type='number';input.min=min;input.max=max;input.step='1';input.disabled=true;input.dataset.prop=prop;panel.querySelector('#trb-studio-spacing').append(l,input);input.addEventListener('input',()=>{if(!selected||input.value===''||!input.checkValidity())return;const change=pending.get(selected.item.key)||{key:selected.item.key,html:selected.item.html,spacing:{}};change.spacing[prop]=Number(input.value);selected.e.style.setProperty(prop,input.value+'px','important');pending.set(change.key,change);save.disabled=false;status.textContent='Anteprima aggiornata. Modifiche non ancora salvate.';});}
 document.addEventListener('click',event=>{if(panel.contains(event.target))return;const e=event.target.closest('[data-trb-studio-key]');if(!e)return;event.preventDefault();event.stopPropagation();if(selected)delete selected.e.dataset.trbStudioSelected;selected=targets.get(e.dataset.trbStudioKey);e.dataset.trbStudioSelected='1';text.disabled=false;text.value=e.innerText;for(const input of panel.querySelectorAll('input[data-prop]')){input.disabled=false;const n=parseFloat(getComputedStyle(e).getPropertyValue(input.dataset.prop));input.value=Number.isFinite(n)?Math.round(n):'';}},true);
 text.addEventListener('input',()=>{if(!selected)return;selected.e.textContent=text.value;const change=pending.get(selected.item.key)||{key:selected.item.key,spacing:{}};change.html=selected.e.innerHTML;pending.set(change.key,change);save.disabled=false;status.textContent='Anteprima aggiornata. Il testo sostituito usa formattazione semplice.';});
 const unload=event=>{if(pending.size){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',unload);
 panel.querySelector('#trb-studio-cancel').addEventListener('click',()=>{if(pending.size&&!confirm('Scartare le modifiche non salvate?'))return;pending.clear();location.assign(c.exit);});
 save.addEventListener('click',async()=>{save.disabled=true;text.disabled=true;panel.querySelectorAll('input').forEach(e=>e.disabled=true);status.textContent='Salvataggio…';try{await request('POST',{version:manifest.version,changes:[...pending.values()]});pending.clear();status.textContent='Salvato.';location.assign(c.exit);}catch(e){status.textContent=e.message;save.disabled=false;text.disabled=!selected;panel.querySelectorAll('input').forEach(el=>el.disabled=!selected);}});
})();
