<?php
if(PHP_SAPI!=='cli')exit;ini_set('display_errors','0');ob_start();
$code= <<<'CODE'
$_SERVER['HTTP_HOST']='artist.trbrec.com';$_SERVER['REQUEST_URI']='/';$_SERVER['HTTPS']='on';define('WP_USE_THEMES',false);define('DISABLE_WP_CRON',true);ob_start();require '/home/customer/www/artist.trbrec.com/public_html/wp-load.php';
$id=(int)get_option('wp_page_for_privacy_policy');$p=$id?get_post($id):get_post(9258);$url=get_privacy_policy_url();$src=file_get_contents('/home/customer/www/artist.trbrec.com/public_html/wp-content/themes/docy/tools/finish-onboarding-privacy.php');preg_match("/\$notice= <<<'NOTICE'\n(.*?)\nNOTICE;/s",$src,$match);
$r=['page_id'=>$p?$p->ID:null,'status'=>$p?$p->post_status:null,'configured_id'=>$id,'version'=>$p?get_post_meta($p->ID,'_trb_onboarding_privacy_version',true):null,'url'=>$url,'content_length'=>$p?strlen($p->post_content):null,'expected_found'=>isset($match[1]),'content_matches'=>$p&&isset($match[1])&&$p->post_content===$match[1]];
if($p&&isset($match[1])&&!$r['content_matches']){$a=$p->post_content;$b=$match[1];$i=0;while($i<min(strlen($a),strlen($b))&&$a[$i]===$b[$i])$i++;$r['difference']=['offset'=>$i,'stored'=>substr($a,max(0,$i-40),180),'expected'=>substr($b,max(0,$i-40),180)];}
foreach(['privacy'=>$url,'candidate'=>'https://artist.trbrec.com/adesione/?trb_privacy_check=20261002c'] as $key=>$u){$response=wp_remote_get($u,['timeout'=>30,'redirection'=>0,'headers'=>['Cache-Control'=>'no-cache']]);$body=is_wp_error($response)?'':wp_remote_retrieve_body($response);$r[$key]=['error'=>is_wp_error($response),'code'=>is_wp_error($response)?null:wp_remote_retrieve_response_code($response),'location'=>is_wp_error($response)?null:wp_remote_retrieve_header($response,'location'),'privacy_marker'=>str_contains($body,'trb-onboarding-privacy'),'privacy_link'=>$url!==''&&str_contains($body,esc_url($url)),'instant_copy'=>str_contains($body,'PayPal o una carta di credito/debito'),'old_bank_copy'=>str_contains($body,'Per il bonifico')];}
while(ob_get_level())ob_end_clean();echo json_encode($r,JSON_UNESCAPED_SLASHES);
CODE;
exec(escapeshellarg(PHP_BINARY).' -r '.escapeshellarg($code).' 2>/dev/null',$lines,$status);while(ob_get_level())ob_end_clean();echo json_encode(['privacy_diagnostic'=>implode("\n",$lines),'exit'=>$status])."\n";
