<?php
if(PHP_SAPI!=='cli')exit;ini_set('display_errors','0');ob_start();
set_exception_handler(static function(){while(ob_get_level())ob_end_clean();fwrite(STDERR,"Registration state diagnostic unconfirmed.\n");exit(1);});
$root='/home/customer/www/crm.trbrec.com/public_html';require $root.'/app/Core.php';\TrbCrm\Env::load($root.'/.env');require $root.'/app/OnboardingRuntime.php';
$db=\TrbCrm\Database::connection();$ledger=new \TrbCrm\OnboardingLedger($db);$p=$ledger->forContract(26);
if(!$p||$p['email']!=='a.tognassi@gmail.com'||$p['snapshot']['contract_number']!=='QA-TRB-NONVALIDO-20261002-2235')throw new RuntimeException('Scope');
$q=$db->prepare('SELECT payload FROM onboarding_events WHERE event_key=?');$q->execute(['onboarding:'.$p['id'].':portal-active']);$bound=(int)(json_decode((string)$q->fetchColumn(),true)['portal_user_id']??0);
$code='define("WP_USE_THEMES",false);define("DISABLE_WP_CRON",true);require "/home/customer/www/artist.trbrec.com/public_html/wp-load.php";$u=get_user_by("email","a.tognassi@gmail.com");$a=function_exists("pw_new_user_approve")?pw_new_user_approve():null;$callbacks=[];global $wp_filter;foreach(($wp_filter["user_register"]->callbacks??[]) as $priority=>$list)foreach($list as $entry){$f=$entry["function"];if(is_array($f))$callbacks[]=["priority"=>$priority,"class"=>is_object($f[0])?get_class($f[0]):$f[0],"method"=>$f[1]];} $source=[];if($a){$r=new ReflectionClass($a);$lines=file($r->getFileName());foreach($lines as $line)if(str_contains($line,"apply_filters(")||str_contains($line,"add_action(")||str_contains($line,"function notify")||str_contains($line,"function send"))$source[]=trim($line);}echo json_encode(["exists"=>(bool)$u,"same_practice"=>$u?get_user_meta($u->ID,"_trb_onboarding_practice",true)==='.var_export($p['id'],true).':false,"matches_crm_user"=>$u?$u->ID==='.var_export($bound,true).':false,"stage"=>$u?get_user_meta($u->ID,"_trb_onboarding_stage",true):null,"version"=>$u?get_user_meta($u->ID,"_trb_onboarding_version",true):null,"qa"=>$u?get_user_meta($u->ID,"_trb_onboarding_qa",true):null,"profile"=>$u?get_user_meta($u->ID,"_trb_artist_contract_profile",true):null,"approval_status"=>$u&&$a?$a->get_user_status($u->ID):null,"approval_callbacks"=>$callbacks,"approval_source_hooks"=>$source]);';
exec(escapeshellarg(PHP_BINARY).' -r '.escapeshellarg($code).' 2>/dev/null',$lines,$status);$wp=json_decode(implode("\n",$lines),true);if($status!==0||!is_array($wp))throw new RuntimeException('WP');
$out=['crm_state'=>$p['state'],'portal_activation_recorded'=>(bool)$p['portal_activated_at'],'portal'=>$wp];while(ob_get_level())ob_end_clean();echo json_encode($out,JSON_UNESCAPED_SLASHES)."\n";
