<?php
if(PHP_SAPI!=='cli')exit;ini_set('display_errors','0');ob_start();
set_exception_handler(static function(){while(ob_get_level())ob_end_clean();fwrite(STDERR,"Registration state diagnostic unconfirmed.\n");exit(1);});
$root='/home/customer/www/crm.trbrec.com/public_html';require $root.'/app/Core.php';\TrbCrm\Env::load($root.'/.env');require $root.'/app/OnboardingRuntime.php';
$db=\TrbCrm\Database::connection();$ledger=new \TrbCrm\OnboardingLedger($db);$p=$ledger->forContract(26);
if(!$p||$p['email']!=='a.tognassi@gmail.com'||$p['snapshot']['contract_number']!=='QA-TRB-NONVALIDO-20261002-2235')throw new RuntimeException('Scope');
$q=$db->prepare('SELECT payload FROM onboarding_events WHERE event_key=?');$q->execute(['onboarding:'.$p['id'].':portal-active']);$bound=(int)(json_decode((string)$q->fetchColumn(),true)['portal_user_id']??0);
$code='define("WP_USE_THEMES",false);define("DISABLE_WP_CRON",true);require "/home/customer/www/artist.trbrec.com/public_html/wp-load.php";$source=[];$a=pw_new_user_approve();foreach(["approve_user","do_password_reset","request_admin_approval_email_2"] as $name){if(!method_exists($a,$name))continue;$m=new ReflectionMethod($a,$name);$lines=file($m->getFileName());$source[$name]=implode("",array_slice($lines,$m->getStartLine()-1,$m->getEndLine()-$m->getStartLine()+1));}global $wp_filter;foreach(($wp_filter["user_register"]->callbacks??[]) as $list)foreach($list as $entry){$f=$entry["function"];if(is_array($f)&&is_object($f[0])&&$f[1]==="pendingApproval"){$m=new ReflectionMethod($f[0],$f[1]);$source["download_manager_pending"]=implode("",array_slice(file($m->getFileName()),$m->getStartLine()-1,$m->getEndLine()-$m->getStartLine()+1));}}echo json_encode($source);';
exec(escapeshellarg(PHP_BINARY).' -r '.escapeshellarg($code).' 2>/dev/null',$lines,$status);$wp=json_decode(implode("\n",$lines),true);if($status!==0||!is_array($wp))throw new RuntimeException('WP');
$out=['approval_source'=>$wp];while(ob_get_level())ob_end_clean();echo json_encode($out,JSON_UNESCAPED_SLASHES)."\n";
