<?php
/** Explicitly authorized retirement of the owner's previous signed TRB test account. */
if(PHP_SAPI!=='cli')exit;ini_set('display_errors','0');ob_start();$stage='bootstrap';
set_exception_handler(static function()use(&$stage){while(ob_get_level())ob_end_clean();fwrite(STDERR,"Owner TRB test retirement unconfirmed at ".$stage.".\n");exit(1);});
$root='/home/customer/www/crm.trbrec.com/public_html';require $root.'/app/Core.php';\TrbCrm\Env::load($root.'/.env');require $root.'/app/OnboardingRuntime.php';
$theme='/home/customer/www/artist.trbrec.com/public_html/wp-content/themes/docy';if(trim(file_get_contents($theme.'/.trb-deployed-sha'))!=='09c6b725aca95c0642aebc3534455c61b0bbd3c6')exit(2);
$db=\TrbCrm\Database::connection();$lock=$db->query("SELECT GET_LOCK('trb_owner_ddb600_test_reset',0)");if((int)$lock->fetchColumn()!==1)throw new RuntimeException();
try{
$owner=$db->query("SELECT id,role,email FROM users WHERE email='andrea.tognassi@trbrec.com' AND role='admin' AND is_active=1")->fetch();if(!$owner)throw new RuntimeException();
$ledger=new \TrbCrm\OnboardingLedger($db);$p=$ledger->forContract(26);if(!$p||$p['email']!=='a.tognassi@gmail.com'||$p['snapshot']['contract_number']!=='QA-TRB-NONVALIDO-20261002-2235'||$p['snapshot']['template_key']!=='trb_ccde'||!in_array($p['state'],['active','cancelled'],true))throw new RuntimeException();
$preserved=[$ledger->artifact($p['id'],'signed_pdf'),$ledger->artifact($p['id'],'signature_audit')];if(!$preserved[0]||!$preserved[1]||($ledger->signature($p['id'])['state']??'')!=='completed')throw new RuntimeException();
$q=$db->prepare('SELECT payload FROM onboarding_events WHERE event_key=?');$q->execute(['onboarding:'.$p['id'].':portal-active']);$bound=(int)(json_decode((string)$q->fetchColumn(),true)['portal_user_id']??0);if(!$bound)throw new RuntimeException();
$setup='$_SERVER["HTTP_HOST"]="artist.trbrec.com";$_SERVER["REQUEST_URI"]="/";$_SERVER["HTTPS"]="on";define("WP_USE_THEMES",false);define("DISABLE_WP_CRON",true);ob_start();require "/home/customer/www/artist.trbrec.com/public_html/wp-load.php";';
$guard='$u=get_user_by("email","a.tognassi@gmail.com");$same=$u&&$u->ID==='.var_export($bound,true).'&&get_user_meta($u->ID,"_trb_onboarding_practice",true)==='.var_export($p['id'],true).'&&get_user_meta($u->ID,"_trb_onboarding_version",true)==="2026.2"&&get_user_meta($u->ID,"_trb_artist_contract_profile",true)==="trb"&&get_user_meta($u->ID,"_trb_artist_preliminary_contract",true)==="QA-TRB-NONVALIDO-20261002-2235"&&get_user_meta($u->ID,"_trb_onboarding_qa",true)==="1"&&trb_portal_is_release_qa_account($u)&&!$u->has_cap("manage_options");global $wpdb;$posts=$u?(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_author=%d",$u->ID)):0;$comments=$u?(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->comments} WHERE user_id=%d",$u->ID)):0;$local=0;foreach((array)($u?get_user_meta($u->ID,"_trb_artist_private_files",true):[]) as $f)if(is_array($f)&&!empty($f["path"]))$local++;';
$stage='exact-account-preflight';$code=$setup.$guard.'while(ob_get_level())ob_end_clean();echo json_encode(["exists"=>(bool)$u,"same_bound_test"=>(bool)$same,"owned_posts"=>$posts,"owned_comments"=>$comments,"local_files"=>$local]);';$lines=[];exec(escapeshellarg(PHP_BINARY).' -r '.escapeshellarg($code).' 2>/dev/null',$lines,$exit);$check=$exit===0?json_decode(implode("\n",$lines),true):null;
if(!is_array($check)||($check['exists']&&(!$check['same_bound_test']||$check['owned_posts']!==0||$check['owned_comments']!==0||$check['local_files']!==0)))throw new RuntimeException();
$stage='retire-previous-invitation';$ledger->cancel($p['id'],$owner);
$stage='delete-bound-qa-account';$code=$setup.$guard.'if($u){if(!$same||$posts||$comments||$local)exit(3);require_once ABSPATH."wp-admin/includes/user.php";if(!wp_delete_user($u->ID))exit(4);}clean_user_cache('.var_export($bound,true).');$absent=!get_user_by("email","a.tognassi@gmail.com")&&!get_userdata('.var_export($bound,true).');while(ob_get_level())ob_end_clean();echo json_encode(["account_absent"=>$absent]);';$lines=[];exec(escapeshellarg(PHP_BINARY).' -r '.escapeshellarg($code).' 2>/dev/null',$lines,$exit);$deleted=$exit===0?json_decode(implode("\n",$lines),true):null;if(($deleted['account_absent']??false)!==true)throw new RuntimeException();
$stage='archive-preservation';if($ledger->practice($p['id'])['state']!=='cancelled'||$preserved!==[$ledger->artifact($p['id'],'signed_pdf'),$ledger->artifact($p['id'],'signature_audit')])throw new RuntimeException();
$out=['success'=>true,'old_test_account_deleted'=>true,'old_invitation_retired'=>true,'signed_contract_and_signature_audit_preserved'=>true,'production_accounts_touched'=>false];
while(ob_get_level())ob_end_clean();echo json_encode($out)."\n";
}finally{$db->query("SELECT RELEASE_LOCK('trb_owner_ddb600_test_reset')");}
