<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/integrations/onboarding/crm/OnboardingLedger.php';
use TrbCrm\OnboardingPolicy as Policy;
use TrbCrm\OnboardingLedger as Ledger;
function check(bool $ok,string $label): void {if(!$ok)throw new RuntimeException($label);}
function rejects(callable $fn,string $label): void {try{$fn();}catch(Throwable $e){return;}throw new RuntimeException($label);}
$plan=['kind'=>'monthly','currency'=>'EUR','amounts_cents'=>array_fill(0,10,20000),'total_cents'=>200000,'discount_basis_points'=>0,'source_sha256'=>str_repeat('a',64),'service_grace_days'=>0];
$schedule=Policy::schedule($plan,'2026-10-01');
check($schedule[1]['due_date']==='2026-11-01'&&$schedule[9]['due_date']==='2027-07-01','10 consecutive contractual installments');
check(Policy::dueDate('2026-01-31',1)==='2026-02-28'&&Policy::dueDate('2026-01-31',2)==='2026-03-31','end of month does not drift');
check(Policy::dueDate('2028-01-31',1)==='2028-02-29','leap month');
$identity=['first_name'=>'Mario','last_name'=>'De Luca'];
check(Policy::identity($identity,['legible'=>true,'first_name'=>'Mario Luigi','last_name'=>'DE LUCA','birth_date'=>'2008-09-30'],'2026-09-30')['status']==='matched','second first name optional and adult birthday inclusive');
check(Policy::identity($identity,['legible'=>true,'first_name'=>'Mario','last_name'=>'De Luca','birth_date'=>'2008-10-01'],'2026-09-30')['reason']==='minor','day before eighteen');
check(Policy::identity($identity,['legible'=>true,'first_name'=>'Mario','last_name'=>'Luca','birth_date'=>'1990-01-01'],'2026-09-30')['reason']==='name_mismatch','full compound surname required');
check(Policy::identity($identity,['legible'=>true,'first_name'=>'Marion','last_name'=>'De Luca','birth_date'=>'1990-01-01'],'2026-09-30')['reason']==='name_mismatch','no fuzzy or substring names');
check(Policy::identity($identity,['legible'=>true,'first_name'=>'Mario','last_name'=>'De Luca','birth_date'=>'1990-02-31'],'2026-09-30')['status']==='review','invalid OCR date');
check(Policy::identity($identity,['legible'=>false],'2026-09-30')['status']==='review','unreadable is never approved');
check(Policy::identity(['first_name'=>'Jean','last_name'=>'Durand'],['legible'=>true,'first_name'=>'Jean-Pierre','last_name'=>'Durand','birth_date'=>'1990-01-01'],'2026-09-30')['status']==='review','hyphenated given name must match whole');
$twoFronts=['legible'=>true,'first_name'=>'Mario Luigi','last_name'=>'De Luca','birth_date'=>'1990-01-01','expiry_date'=>'2030-01-01','tax_legible'=>true,'tax_first_name'=>'Mario Luigi','tax_last_name'=>'De Luca','tax_birth_date'=>'1990-01-01','tax_code'=>'DLCMRA90A01H501A'];
check(Policy::documents($identity,$twoFronts,'DLCMRA90A01H501A','2026-09-30')['status']==='matched','two matching fronts accepted');
foreach(['tax_legible'=>false,'tax_first_name'=>'Carlo','tax_last_name'=>'Rossi','tax_birth_date'=>'1991-01-01','tax_code'=>'DLCMRA90A01H501B','expiry_date'=>'2020-01-01'] as $field=>$value)check(Policy::documents($identity,array_replace($twoFronts,[$field=>$value]),'DLCMRA90A01H501A','2026-09-30')['status']==='review','inconsistent '.$field.' never accepted');
check(Policy::documents($identity,array_replace($twoFronts,['expiry_date'=>'2026-09-30']),'DLCMRA90A01H501A','2026-09-30')['status']==='matched','identity valid throughout expiry date');
rejects(fn()=>Policy::validatePlan(array_replace($plan,['total_cents'=>199999])),'cents cannot be lost');
$practice=['onboarding_version'=>Policy::VERSION,'owner_approved_at'=>'2026-10-01','signed_at'=>'2026-10-01','signed_pcloud_file_id'=>123,'portal_activated_at'=>'2026-10-01'];
$rows=[['number'=>1,'due_date'=>'2026-10-01','amount_cents'=>20000,'confirmed_cents'=>20000],['number'=>2,'due_date'=>'2026-11-01','amount_cents'=>20000,'confirmed_cents'=>0]];
check(Policy::services($practice,$rows,'2026-11-01')['allowed'],'rata can be paid throughout due date');
check(!Policy::services($practice,$rows,'2026-11-02')['allowed'],'services blocked next local day');
check(!Policy::services($practice,$rows,'2026-11-05')['allowed'],'user November fifth example');
$rows[1]['confirmed_cents']=20000;
check(Policy::services($practice,$rows,'2026-11-05')['allowed'],'confirmed payment reopens services');
$rows[1]['confirmed_cents']=19999;
check(!Policy::services($practice,$rows,'2026-11-05')['allowed'],'partial payment does not unlock');
check(Policy::services([], $rows,'2026-11-05')['managed']===false,'legacy accounts unchanged');
check(!Policy::services(array_replace($practice,['owner_approved_at'=>null]),$rows,'2026-10-01')['allowed'],'no owner bypass');
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$ledger=new Ledger($pdo);$ledger->install();$ledger->install();
$snapshot=['onboarding_version'=>Policy::VERSION,'unsigned_document_sha256'=>str_repeat('b',64),'artist_folder_id'=>333,'email'=>'qa@example.invalid','first_name'=>'Mario','last_name'=>'De Luca','group_code'=>'DDB-TRB','plans'=>['A'=>$plan]];
$invite=$ledger->create(999,$snapshot,gmdate('c',time()+86400));$id=$invite['id'];
check($ledger->fromToken($invite['token'])['id']===$id,'opaque invitation resolves only own practice');
rejects(fn()=>$ledger->fromToken(str_repeat('f',64)),'unrelated token rejected');
rejects(fn()=>$ledger->choosePlan($id,'A'),'documents precede checkout');
$challenge=$ledger->challenge($invite['token']);
rejects(fn()=>$ledger->verifyEmail($invite['token'],'000000',$challenge['salt']),'wrong email possession code rejected');
$session=$ledger->verifyEmail($invite['token'],$challenge['code'],$challenge['salt']);
check($ledger->fromSession($session)['id']===$id,'verified session bound to one practice');
rejects(fn()=>$ledger->verifyEmail($invite['token'],$challenge['code'],$challenge['salt']),'email code consumed once');
$ledger->saveDetails($id,['privacy_acknowledged_at'=>gmdate('c'),'tax_code'=>'DLCMRA90A01H501A']);
foreach(['identity_front','tax_front'] as $i=>$slot)$ledger->recordFile($id,$slot,['file_id'=>100+$i,'folder_id'=>200+$i,'hash'=>'pcloud-hash-'.$i]);
check($ledger->recordIdentity($id,['legible'=>true,'first_name'=>'Mario Luigi','last_name'=>'De Luca','birth_date'=>'1990-01-01','expiry_date'=>'2030-01-01','tax_legible'=>true,'tax_first_name'=>'Mario Luigi','tax_last_name'=>'De Luca','tax_birth_date'=>'1990-01-01','tax_code'=>'DLCMRA90A01H501A'],'2026-09-30')['status']==='matched','actual document state precedes checkout');
rejects(fn()=>$ledger->saveDetails($id,['tax_code'=>'OTHER']),'verified administrative data cannot change before plan selection');
$ledger->choosePlan($id,'A');
rejects(fn()=>$ledger->recordFile($id,'identity_front',['file_id'=>999,'folder_id'=>200,'hash'=>'other']),'documents immutable after identity acceptance');
$proof=['provider'=>'woocommerce','transaction_id'=>'order:123:txn:456','amount_cents'=>20000,'currency'=>'EUR','paid_on'=>'2026-10-01','status'=>'confirmed'];
rejects(fn()=>$ledger->confirmedPayment($id,1,array_replace($proof,['status'=>'pending'])),'pending capture blocked');
rejects(fn()=>$ledger->confirmedPayment($id,1,array_replace($proof,['amount_cents'=>19999])),'wrong checkout total rejected atomically');
check($ledger->installments($id)===[],'failed confirmation rolled back schedule');
$ledger->confirmedPayment($id,1,$proof);$ledger->confirmedPayment($id,1,$proof);
check(count($ledger->installments($id))===10 && (int)$ledger->installments($id)[0]['confirmed_cents']===20000,'duplicate webhook counted once');
rejects(fn()=>$ledger->confirmedPayment($id,3,array_replace($proof,['transaction_id'=>'order:124:txn:457','paid_on'=>'2026-12-01'])),'cannot skip a previous debt');
$owner=['id'=>1,'email'=>'owner@example.invalid','role'=>'admin'];
rejects(fn()=>$ledger->reserveSignature($id,str_repeat('c',64),str_repeat('d',64),'2026-10-01'),'no chargeable signature before owner approval');
rejects(fn()=>$ledger->approve($id,array_replace($owner,['role'=>'operator']),$owner['email'],'2026-10-01'),'operator cannot bypass owner');
rejects(fn()=>$ledger->approve($id,$owner,'other@example.invalid','2026-10-01'),'different administrator cannot bypass owner');
$ledger->approve($id,$owner,$owner['email'],'2026-10-01');
$sig=$ledger->reserveSignature($id,str_repeat('c',64),str_repeat('d',64),'2026-10-01');
check($sig['dispatch']===true && $ledger->reserveSignature($id,str_repeat('c',64),str_repeat('d',64),'2026-10-01')['dispatch']===false,'one provider dispatch even after crash and retry');
rejects(fn()=>$ledger->reserveSignature($id,str_repeat('e',64),str_repeat('d',64),'2026-10-01'),'approved signature document cannot change');
$ledger->signatureDispatched($id,$sig['request_key'],'dossier-qa');
$signed=['status'=>'completed','artist_signed'=>true,'company_signed'=>true,'request_key'=>$sig['request_key'],'document_sha256'=>str_repeat('c',64),'dossier_id'=>'dossier-qa','file'=>['file_id'=>123,'artist_folder_id'=>333,'sha256'=>str_repeat('f',64)]];
rejects(fn()=>$ledger->completeSignature($id,array_replace($signed,['company_signed'=>false])),'both signatures necessary');
$ledger->completeSignature($id,$signed);$ledger->completeSignature($id,$signed);
check(!$ledger->access($id,'2026-10-01')['allowed'],'signed document alone does not activate a portal account');
$ledger->markActivated($id,1234);
check($ledger->queueOverdueReminders('2026-11-01')===0,'no reminder on due day');
check($ledger->queueOverdueReminders('2026-11-02')===1 && $ledger->queueOverdueReminders('2026-11-03')===0,'one reminder per installment across repeated cron');
$ledger->confirmedPayment($id,2,array_replace($proof,['transaction_id'=>'order:124:txn:457','paid_on'=>'2026-11-05']));
check($ledger->access($id,'2026-11-05')['allowed'],'ledger clears debt using confirmed proof');
$ledger->reversePayment('woocommerce','order:124:txn:457');
check(!$ledger->access($id,'2026-11-05')['allowed'],'refund reopens original debt');
rejects(fn()=>$ledger->confirmedPayment($id,2,array_replace($proof,['transaction_id'=>'order:124:txn:457','paid_on'=>'2026-11-05'])),'late payment webhook cannot undo refund');
$ledger->confirmedPayment($id,2,array_replace($proof,['transaction_id'=>'order:125:txn:458','paid_on'=>'2026-11-05']));
$ledger->reversePayment('woocommerce','order:125:txn:458',1500);
check((int)$ledger->installments($id)[1]['confirmed_cents']===18500,'partial refund reopens only the refunded cents');
$ledger->reversePayment('woocommerce','order:125:txn:458',1500);
check((int)$ledger->installments($id)[1]['confirmed_cents']===18500,'repeated cumulative refund is idempotent');
rejects(fn()=>$ledger->reversePayment('woocommerce','order:125:txn:458',1000),'out-of-order refund cannot restore money');
$ledger->confirmedPayment($id,2,array_replace($proof,['transaction_id'=>'order:126:txn:459','amount_cents'=>1500,'paid_on'=>'2026-11-06']));
check($ledger->access($id,'2026-11-06')['allowed'],'verified exact residual payment clears partial refund');
echo "Onboarding identity, plans, calendar, payment idempotency, suspension and reminders verified.\n";
