<?php
/** One revision-bound OCR probe with fictional data. No candidate records or customer documents. */
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
ini_set('display_errors','0');
set_exception_handler(static function(){fwrite(STDERR,"Synthetic document reading unconfirmed.\n");exit(1);});
$theme=dirname(__DIR__);$revision=$argv[1]??'';
if(!preg_match('/^[a-f0-9]{40}$/D',$revision)||trim((string)@file_get_contents($theme.'/.trb-deployed-sha'))!==$revision)exit(2);
$crm='/home/customer/www/crm.trbrec.com/public_html';
require_once $crm.'/app/Core.php';\TrbCrm\Env::load($crm.'/.env');
require_once $crm.'/app/OnboardingIdentity.php';
$reader=new \TrbCrm\OnboardingIdentity((string)\TrbCrm\Env::get('OPENAI_API_KEY',''));
$result=$reader->extract([['mime'=>'application/pdf','data'=>'JVBERi0xLjMKJZOMi54gUmVwb3J0TGFiIEdlbmVyYXRlZCBQREYgZG9jdW1lbnQgKG9wZW5zb3VyY2UpCjEgMCBvYmoKPDwKL0YxIDIgMCBSIC9GMiAzIDAgUgo+PgplbmRvYmoKMiAwIG9iago8PAovQmFzZUZvbnQgL0hlbHZldGljYSAvRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZyAvTmFtZSAvRjEgL1N1YnR5cGUgL1R5cGUxIC9UeXBlIC9Gb250Cj4+CmVuZG9iagozIDAgb2JqCjw8Ci9CYXNlRm9udCAvSGVsdmV0aWNhLUJvbGQgL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcgL05hbWUgL0YyIC9TdWJ0eXBlIC9UeXBlMSAvVHlwZSAvRm9udAo+PgplbmRvYmoKNCAwIG9iago8PAovQ29udGVudHMgOCAwIFIgL01lZGlhQm94IFsgMCAwIDU5NS4yNzU2IDg0MS44ODk4IF0gL1BhcmVudCA3IDAgUiAvUmVzb3VyY2VzIDw8Ci9Gb250IDEgMCBSIC9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSSBdCj4+IC9Sb3RhdGUgMCAvVHJhbnMgPDwKCj4+IAogIC9UeXBlIC9QYWdlCj4+CmVuZG9iago1IDAgb2JqCjw8Ci9QYWdlTW9kZSAvVXNlTm9uZSAvUGFnZXMgNyAwIFIgL1R5cGUgL0NhdGFsb2cKPj4KZW5kb2JqCjYgMCBvYmoKPDwKL0F1dGhvciAoYW5vbnltb3VzKSAvQ3JlYXRpb25EYXRlIChEOjIwMjYxMDAxMDU1ODA1LTA1JzAwJykgL0NyZWF0b3IgKGFub255bW91cykgL0tleXdvcmRzICgpIC9Nb2REYXRlIChEOjIwMjYxMDAxMDU1ODA1LTA1JzAwJykgL1Byb2R1Y2VyIChSZXBvcnRMYWIgUERGIExpYnJhcnkgLSBcKG9wZW5zb3VyY2VcKSkgCiAgL1N1YmplY3QgKHVuc3BlY2lmaWVkKSAvVGl0bGUgKHVudGl0bGVkKSAvVHJhcHBlZCAvRmFsc2UKPj4KZW5kb2JqCjcgMCBvYmoKPDwKL0NvdW50IDEgL0tpZHMgWyA0IDAgUiBdIC9UeXBlIC9QYWdlcwo+PgplbmRvYmoKOCAwIG9iago8PAovRmlsdGVyIFsgL0FTQ0lJODVEZWNvZGUgL0ZsYXRlRGVjb2RlIF0gL0xlbmd0aCAzMDIKPj4Kc3RyZWFtCkdhcm87Oyw7ZnUnU1lIPS8nYW5HT2A+QU5aOFo9RU9Bbz5Ubz1dXU1DQmNYbUlHaV5dKTo9a15vVlE9dG1XWnIqXzA6W1NdNHVrQ0pdLl9CIWYtcWxrcSsmPFIkYGtaITRyJ1kiN2o8OVNMMDhbTzdoNF5CUTFBPTc+YGtGIjs+TDRAYEpnJDNUb3BdUylYXGovJ0U/cWtFdEU5IikhWkxCNi9rZk0hTFpdPSE4UDY2c2ZBNCdWMXNSZSMzX0lBPl1tcltkS0NYQ05ZQWI7bkt1XFptL1M8Xj1TXydEbDpvUC5vQyloWkVMWCMpdS1kWjZXKW9PQTY3YEgvWlZyUU83W2QzNTJBUkhOdFNtQjxoMTs9QmJmXWEyMyJ0aChnTilGayhxXCxpayZoWX4+ZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgOQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwNjEgMDAwMDAgbiAKMDAwMDAwMDEwMiAwMDAwMCBuIAowMDAwMDAwMjA5IDAwMDAwIG4gCjAwMDAwMDAzMjEgMDAwMDAgbiAKMDAwMDAwMDUyNCAwMDAwMCBuIAowMDAwMDAwNTkyIDAwMDAwIG4gCjAwMDAwMDA4NTMgMDAwMDAgbiAKMDAwMDAwMDkxMiAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9JRCAKWzxjM2Y0ZGY1NWMzMjc0NzBjODhhMzAzMzE0NDdjN2Q2Nz48YzNmNGRmNTVjMzI3NDcwYzg4YTMwMzMxNDQ3YzdkNjc+XQolIFJlcG9ydExhYiBnZW5lcmF0ZWQgUERGIGRvY3VtZW50IC0tIGRpZ2VzdCAob3BlbnNvdXJjZSkKCi9JbmZvIDYgMCBSCi9Sb290IDUgMCBSCi9TaXplIDkKPj4Kc3RhcnR4cmVmCjEzMDQKJSVFT0YK','name'=>'dati-sintetici-qa.pdf']]);
if(($result['legible']??false)!==true||\TrbCrm\OnboardingPolicy::normalizedName($result['first_name']??'')!=='mario andrea'||\TrbCrm\OnboardingPolicy::normalizedName($result['last_name']??'')!=='rossi'||($result['birth_date']??'')!=='1990-01-01')throw new RuntimeException('Synthetic OCR mismatch');
echo "Synthetic OpenAI document reading verified.\n";
