<?php
if(PHP_SAPI!=='cli')exit;ini_set('display_errors','0');ob_start();$stage='bootstrap';
set_exception_handler(static function(){global $stage;while(ob_get_level())ob_end_clean();fwrite(STDERR,"Registration completion audit unconfirmed at ".$stage.".\n");exit(1);});
$root='/home/customer/www/crm.trbrec.com/public_html';require $root.'/app/Core.php';\TrbCrm\Env::load($root.'/.env');require $root.'/app/OnboardingRuntime.php';
$db=\TrbCrm\Database::connection();$ledger=new \TrbCrm\OnboardingLedger($db);$p=$ledger->forContract(26);
if(!$p||$p['email']!=='a.tognassi@gmail.com'||$p['snapshot']['contract_number']!=='QA-TRB-NONVALIDO-20261002-2235')throw new RuntimeException('Scope');
$stage='revision';$expected='594f4b5c449d3377899843af4e54ad5c9e60e09a';if(trim(file_get_contents('/home/customer/www/artist.trbrec.com/public_html/wp-content/themes/docy/.trb-deployed-sha'))!==$expected)throw new RuntimeException('Revision');
$q=$db->prepare('SELECT payload FROM onboarding_events WHERE event_key=?');$q->execute(['onboarding:'.$p['id'].':portal-active']);$bound=(int)(json_decode((string)$q->fetchColumn(),true)['portal_user_id']??0);
if($p['state']!=='active'||!$p['portal_activated_at']||$bound<1||($ledger->signature($p['id'])['state']??'')!=='completed'||!$ledger->artifact($p['id'],'signed_pdf')||!$ledger->artifact($p['id'],'signature_audit'))throw new RuntimeException('Active signature binding');
$stage='portal';
$code='define("WP_USE_THEMES",false);define("DISABLE_WP_CRON",true);require "/home/customer/www/artist.trbrec.com/public_html/wp-load.php";$u=get_user_by("email","a.tognassi@gmail.com");$a=pw_new_user_approve();$callback=[$a,"request_admin_approval_email_2"];$priority=has_action("user_register",$callback);$scoped=false;if($priority!==false){remove_action("user_register",$callback,$priority);try{$scoped=has_action("user_register",$callback)===false;}finally{add_action("user_register",$callback,$priority);}$scoped=$scoped&&has_action("user_register",$callback)===$priority;}$source=file_get_contents(get_template_directory()."/inc/trb-candidate-onboarding.php");echo json_encode(["account_exists"=>(bool)$u,"same_practice"=>$u?get_user_meta($u->ID,"_trb_onboarding_practice",true)==='.var_export($p['id'],true).':false,"same_crm_user"=>$u?$u->ID==='.var_export($bound,true).':false,"stage"=>$u?get_user_meta($u->ID,"_trb_onboarding_stage",true):null,"approval"=>$u?$a->get_user_status($u->ID):null,"profile"=>$u?get_user_meta($u->ID,"_trb_artist_contract_profile",true):null,"qa_isolated"=>$u?trb_portal_is_release_qa_account($u):false,"wpdm_extra_approval_required"=>function_exists("WPDM")?(bool)WPDM()->user->requiresApproval():false,"legacy_notification_restored"=>$priority!==false,"notification_can_be_scoped"=>$scoped,"cache_refresh_installed"=>str_contains($source,"clean_user_cache((int)"),"ten_character_validation_installed"=>str_contains($source,"<10")]);';
exec(escapeshellarg(PHP_BINARY).' -r '.escapeshellarg($code).' 2>/dev/null',$lines,$status);$wp=json_decode(implode("\n",$lines),true);
if($status!==0||!is_array($wp)||!$wp['same_practice']||!$wp['same_crm_user']||$wp['stage']!=='active'||$wp['approval']!=='approved'||!$wp['notification_can_be_scoped']||!$wp['cache_refresh_installed']||!$wp['ten_character_validation_installed'])throw new RuntimeException('Portal confirmation');
$stage='page';$html=@file_get_contents('https://artist.trbrec.com/adesione/?accesso=1',false,stream_context_create(['http'=>['timeout'=>15]]));
if(!is_string($html)||substr_count($html,'minlength="10"')!==2||str_contains($html,'almeno 14 caratteri'))throw new RuntimeException('Public minimum');
$out=['deployed_revision'=>$expected,'crm_state'=>$p['state'],'signatures_and_archive_verified'=>true,'portal'=>$wp,'public_password_minimum'=>10,'account_recreated'=>false,'password_unchanged'=>true];while(ob_get_level())ob_end_clean();echo json_encode($out,JSON_UNESCAPED_SLASHES)."\n";
